---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: heading
  label: Content
- type: directory
  path: src/pages
  label: Pages
  create: documents
  match: "*.md"
  new_doc_ext: md
  templates:
  - page
  - blocks-page
- type: directory
  path: src/pages/posts
  label: Posts
  create: documents
  match: "**/*"
  new_doc_ext: md
  templates:
  - post
- type: heading
  label: Config
- type: document
  path: src/data/main_menu.json
  label: Nav Menu
- type: document
  path: site-config.json
  label: Site Config
upload_dir: src/images
public_path: "/src/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
instant_preview: true
build:
  preview_command: npm run forestry:publish
  publish_command: npm run forestry:publish
  preview_env:
  - PATH_PREFIX=/
  publish_env:
  - PATH_PREFIX=/
  preview_output_directory: public
  output_directory: public
  instant_preview_command: npm run forestry:preview
